proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=stats_cache:10m max_size=100m inactive=30s use_temp_path=off;

upstream backend {
    server backend:3000;
}


server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend/;
    }
}